wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,3 +26,12 @@ jobs:
 
       - name: Run lints
         run: ./scripts/lint
+  prevent-debug-release:
+    name: Prevent Debug SDK Release
+    runs-on: ${{ github.repository == 'stainless-sdks/increase-ruby' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
+    steps:
+      - name: Debug Mode Failsafe
+        run: |
+          echo "This SDK was built in debug mode, this job is a failsafe to prevent releasing debug SDKs"
+          echo "Remove 'debug: true' from your Stainless config."
+          exit 1
